# For detailed information on configuring the parameter_bridge, please refer to:
# https://github.com/gazebosim/ros_gz/tree/ros2/ros_gz_bridge#example-5-configuring-the-bridge-via-yaml

- topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "battery"
  gz_topic_name: "model/panther/battery/panther_battery/state"
  ros_type_name: "sensor_msgs/msg/BatteryState"
  gz_type_name: "ignition.msgs.BatteryState"
  subscriber_queue: 10
  publisher_queue: 10
  direction: GZ_TO_ROS


# # gz topic published by Sensors plugin
# - ros_topic_name: "pointcloud2"
#   gz_topic_name: "scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: GZ_TO_ROS


# gz topic published by Sensors plugin for lidar (these are the points)
- ros_topic_name: "PointCloud2"
  gz_topic_name: "os_lidar/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

# # gz topic published by Sensors plugin (for lidar) these are the laserscan type messages
# - ros_topic_name: "LaserScan"
#   gz_topic_name: "world/default/model/panther/link/base_link/sensor/ouster_os1_32_sensor/scan/points"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "ignition.msgs.LaserScan"
#   direction: GZ_TO_ROS

## gz topic publised by sensor plugin foe top down camera (these are the images) 
- ros_topic_name: "image"
  gz_topic_name: "/world/default/model/top_down_camera/link/link/sensor/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin for top down camera (these are the camera info)
- ros_topic_name: "camera_info"
  gz_topic_name: "/world/default/model/top_down_camera/link/link/sensor/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS